os:
    - linux

language: node_js
    - "10.15.0"

jdk:
    - oraclejdk8

env:
    - NODE_VERSION="10.15.0"

script: (mvn clean test package)

before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export BUILD_VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
    - export TRAVIS_TAG=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')-$(date +%Y%m%d%H%M%S)
###################################
# NOT GOING TO TAG THINGS FOR NOW #
###################################
#    - git config --local user.name "Darryl L. Pierce"
#    - git config --local user.email "mcpierce@gmail.com"
#    - git tag $TAG_NAME

deploy:
    provider: releases
    api_key: $GITHUB_AUTH_TOKEN
    file_glob: true
    file:
        - "$(find . -name comixed-library-${BUILD_VERSION}-*.jar)"
        - "$(find . -name comixed-tasks-${BUILD_VERSION}-*.jar)"
        - "$(find . -name comixed-rest-api-${BUILD_VERSION}-*.jar)"
        - "$(find . -name comixed-frontend-${BUILD_VERSION}-*.jar)"
        - "$(find . -name comixed-${BUILD_VERSION}-*.jar)"
    skip_cleanup: true
    keep-history: true
    overwrite: true
    on:
        branch: develop

cache:
    directories:
        - ~/.m2/repository
        - comixed-frontend/node_modules
