os:
    - linux

language: node_js
    - "10.15.0"

jdk:
    - openjdk8

env:
    - NODE_VERSION="10.15.0"

before_script:
    - npm install -g @angular/cli prettier

script: (mvn clean test package)

branches:
    only:
        - develop
        - /^release\/.*$/

before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export BUILD_VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
    - export TRAVIS_TAG=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')-$(date +%Y%m%d%H%M%S)
    - export APP_ARTIFACT=$(find . -name comixed-app-*.zip)
###################################
# NOT GOING TO TAG THINGS FOR NOW #
###################################
#    - git config --local user.name "Darryl L. Pierce"
#    - git config --local user.email "mcpierce@gmail.com"
#    - git tag $TAG_NAME

deploy:
    - provider: releases
      api_key: $GITHUB_AUTH_TOKEN
      file_glob: true
      file:
        - ${APP_ARTIFACT}
      skip_cleanup: true
      keep-history: true
      overwrite: true
      on:
        branch: develop
    - provider: releases
      api_key: $GITHUB_AUTH_TOKEN
      file_glob: true
      file:
        - ${APP_ARTIFACT}
      skip_cleanup: true
      keep-history: true
      overwrite: true
      on:
        branch: release\/.*$/

cache:
    directories:
        - $HOME/.m2/repository
        - $TRAVIS_BUILD_DIR/comixed-frontend/node_modules
