# Replace /config-path with the path for your database files.
# Replace /comics-path with the path for your comic files.

version: "3.6"
services:
  comixed:
    image: "comixed/comixed"
    container_name: "comixed"
    environment:
      - TZ=Etc/UTC
    volumes:
      - "/config-path:/root/.comixed"
      - "/comic-path:/comics"
    ports:
      - "0.0.0.0:7171:7171/tcp"
    restart: unless-stopped
