name: "Publish commits on develop"

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup build environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: mvn -B package --file pom.xml -P ci
      - name: Push the release artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            'comixed-app/target/artifacts/comixed-app-*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}