# GOAL: Close issues where the reporter did not follow the bug template.

name: 'Verify Bug Template'

on:
  issues:
    types: [ opened, edited, reopened ]

jobs:
  verify-bug-template:
    if: ${{ contains(github.event.*.labels.*.name, 'bug') }}
    name: Verify bug report uses the provided template
    runs-on: ubuntu-latest
    steps:
      - name: Verify bug report follows template.
        uses: roots/issue-closer@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: '@${issue.user.login} :wave:\n\nThis issue was automatically closed because it did not follow the bug report template. Please edit the issue body using the provided template.'
          issue-pattern: '^(DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT)(Describe The Bug)((.|\n)*)(To Reproduce The Bug)((.|\n)*)(Expected Behavior)'
